"""Authorship (P24) and zero OSIRIS code (P25)."""

import pathlib
import subprocess

import pytest

from tests.conftest import ROOT

OSIRIS = pathlib.Path("/Users/alessandropezzali/Projects/OSIRIS-REFERENCE")


def test_p24_single_author_no_coauthors():
    log = subprocess.run(["git", "log", "--format=%an%x09%ae%x09%cn%n%B%x00"], cwd=ROOT, capture_output=True,
                         text=True, check=True).stdout
    for entry in filter(None, (e.strip() for e in log.split("\x00"))):
        head = entry.splitlines()[0].split("\t")
        assert head[0] == "Alessandro Pezzali" and head[2] == "Alessandro Pezzali", head
        assert "co-authored-by" not in entry.lower()


def significant_lines(path):
    out = set()
    try:
        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            s = " ".join(line.split())
            if len(s) >= 40 and not s.startswith(("#", "//", "*", "import ", "from ")):
                out.add(s)
    except OSError:
        pass
    return out


# ── P25: zero OSIRIS code, assets or data ────────────────────────────────────
# Every repository file is classified by CONTENT, then compared with OSIRIS-REFERENCE:
#   A. source code        — identical file (hash) or shared significant lines
#   B. assets             — identical file (hash) or identical normalized SVG
#   C. data               — identical file (hash) or shared significant lines (records)
#   D. dependency metadata generated by a package manager (npm lockfile) — accepted ONLY if it is structurally a
#      lockfile whose every entry is a third-party registry package with an integrity hash, with no local path or
#      link and no OSIRIS package name; otherwise the file is treated as data (C). Its lines are not compared,
#      because two projects that use the same library share the same registry metadata.
#   other (documentation, LICENSE) — identical file (hash), as in Phase 1.

CODE = (".py", ".ts", ".tsx", ".js", ".mjs", ".cjs", ".jsx", ".css", ".html", ".toml", ".sh")
ASSET = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg", ".woff", ".woff2", ".ttf", ".otf", ".mp4",
         ".webm", ".mp3", ".pdf")
DATA = (".json", ".geojson", ".jsonl", ".csv", ".tsv", ".txt", ".xml", ".yml", ".yaml", ".webmanifest")
REGISTRY = "https://registry.npmjs.org/"


def osiris_index():
    import hashlib
    lines, hashes, svgs, names = set(), set(), set(), set()
    for p in OSIRIS.rglob("*"):
        if not p.is_file() or "node_modules" in p.parts or ".git" in p.parts:
            continue
        data = p.read_bytes()
        hashes.add(hashlib.sha256(data).hexdigest())
        if p.suffix == ".svg":
            svgs.add(hashlib.sha256(b"".join(data.split())).hexdigest())
        if p.suffix in CODE + DATA and p.name not in ("package-lock.json",):
            lines |= significant_lines(p)
        if p.name == "package.json":
            import json
            try:
                names.add(json.loads(data).get("name"))
            except ValueError:
                pass
    return {"lines": lines, "hashes": hashes, "svgs": svgs, "names": {n for n in names if n}}


def lockfile_ok(path, osiris_names):
    """True if the file is a genuine npm lockfile made only of third-party registry packages."""
    import json
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (ValueError, UnicodeDecodeError):
        return False
    if not (isinstance(doc, dict) and isinstance(doc.get("lockfileVersion"), int) and isinstance(doc.get("packages"), dict)):
        return False
    if doc.get("name") in osiris_names:
        return False
    for key, meta in doc["packages"].items():
        if key == "":
            if meta.get("name") in osiris_names:
                return False
            continue
        if not key.startswith("node_modules/") or meta.get("link"):
            return False
        if not str(meta.get("resolved", "")).startswith(REGISTRY) or not str(meta.get("integrity", "")).startswith("sha"):
            return False
    return True


def classify(path, osiris_names):
    if path.name in ("package-lock.json", "npm-shrinkwrap.json") and lockfile_ok(path, osiris_names):
        return "D"
    if path.suffix in ASSET:
        return "B"
    if path.suffix in CODE:
        return "A"
    if path.suffix in DATA or path.name in ("package-lock.json", "npm-shrinkwrap.json"):
        return "C"
    return "other"   # documentation and legal text (.md, LICENSE): compared by hash, as in Phase 1


def osiris_findings(files, index):
    import hashlib
    out = []
    for p in files:
        if not p.is_file():
            continue
        data = p.read_bytes()
        cat = classify(p, index["names"])
        if hashlib.sha256(data).hexdigest() in index["hashes"]:
            out.append((str(p), cat, "identical file"))
            continue
        if cat == "D":
            continue
        if cat == "B" and p.suffix == ".svg" and hashlib.sha256(b"".join(data.split())).hexdigest() in index["svgs"]:
            out.append((str(p), cat, "identical SVG (whitespace-normalized)"))
        if cat in ("A", "C") or p.suffix == ".svg":
            shared = significant_lines(p) & index["lines"]
            if shared:
                out.append((str(p), cat, sorted(shared)[:2]))
    return out


@pytest.fixture(scope="module")
def osiris():
    if not OSIRIS.exists():
        pytest.fail("OSIRIS-REFERENCE not found: cannot verify P25")
    return osiris_index()


def test_p25_no_osiris_code_assets_or_data(osiris):
    files = subprocess.run(["git", "ls-files", "--others", "--cached", "--exclude-standard"], cwd=ROOT,
                           capture_output=True, text=True, check=True).stdout.split()
    findings = osiris_findings([ROOT / f for f in files], osiris)
    assert findings == [], findings[:5]


def _osiris_file(suffixes, min_lines=1):
    for p in sorted(OSIRIS.rglob("*")):
        if p.is_file() and "node_modules" not in p.parts and ".git" not in p.parts and p.suffix in suffixes \
                and p.name != "package-lock.json" and len(significant_lines(p)) >= min_lines:
            return p
    pytest.fail(f"no OSIRIS file with {suffixes} to build the fixture")


def test_p25_detector_fixtures(osiris, tmp_path):
    """Positive and negative fixtures, built at run time (OSIRIS content is never versioned in NEXUM)."""
    import json
    import shutil
    ui = tmp_path / "ui"
    (ui / "src").mkdir(parents=True)
    # negative: NEXUM's genuine npm lockfile (shares registry metadata with OSIRIS's) is accepted as category D
    shutil.copy(ROOT / "ui" / "package-lock.json", ui / "package-lock.json")
    # positive A: OSIRIS source code copied into the UI, renamed
    code = _osiris_file((".ts", ".tsx"), min_lines=3)
    (ui / "src" / "helper.ts").write_text("// NEXUM\n" + code.read_text(encoding="utf-8"), encoding="utf-8")
    # positive B: OSIRIS assets copied (binary identical; SVG reformatted)
    png = _osiris_file((".png",))
    shutil.copy(png, ui / "logo.png")
    svg = _osiris_file((".svg",))
    (ui / "icon.svg").write_bytes(svg.read_bytes().replace(b">", b">\n"))
    # positive C: OSIRIS data records copied into a data file
    data = _osiris_file((".json",), min_lines=5)
    rows = sorted(significant_lines(data))[:5]
    (ui / "places.json").write_text("\n".join(rows), encoding="utf-8")
    # positive D→C: a file named like a lockfile but not genuine registry metadata (local link + OSIRIS code)
    fake = json.loads((ROOT / "ui" / "package-lock.json").read_text())
    fake["packages"]["node_modules/stolen"] = {"version": "1.0.0", "resolved": "file:../OSIRIS-REFERENCE",
                                               "link": True, "note": sorted(significant_lines(code))[0]}
    fake_dir = ui / "nested"
    fake_dir.mkdir()
    (fake_dir / "package-lock.json").write_text(json.dumps(fake, indent=2).replace('"note": ', '"note":\n'),
                                                encoding="utf-8")
    (fake_dir / "package-lock.json").write_text((fake_dir / "package-lock.json").read_text() + "\n" +
                                                sorted(significant_lines(code))[0] + "\n", encoding="utf-8")
    found = {pathlib.Path(p).relative_to(ui).as_posix(): cat for p, cat, _ in
             osiris_findings([p for p in ui.rglob("*") if p.is_file()], osiris)}
    assert "package-lock.json" not in found                    # harmless npm metadata ignored
    assert found.get("src/helper.ts") == "A"                   # copied code detected
    assert found.get("logo.png") == "B"                        # copied binary asset detected
    assert found.get("icon.svg") == "B"                        # copied SVG detected even when reformatted
    assert found.get("places.json") == "C"                     # copied data detected
    assert found.get("nested/package-lock.json") == "C"        # a fake lockfile is not trusted
    assert classify(ROOT / "ui" / "package-lock.json", osiris["names"]) == "D"
