// Every user-visible string of the workspace lives here (W22 scans this catalogue for causal or
// probabilistic wording; new languages can be added later without touching the views).

export const S = {
  appName: "NEXUM",
  motto: "ONE OBJECT. MANY RELATIONS. ONE TIMELINE.",
  searchPlaceholder: "Cerca oggetti, eventi, insight o incolla un ID…",
  searchTooShort: "Almeno 2 caratteri",
  searchNone: "Nessun risultato con i filtri attivi",
  searchUnranked: (n: number | null) =>
    `Risultati non ordinati per rilevanza${n != null ? ` (circa ${n})` : ""}: affina la ricerca`,
  views: { map: "Mappa", graph: "Grafo", split: "Mappa + Grafo", time: "Tempo", search: "Cerca", focus: "Fuoco" },
  kinds: { object: "Oggetto", event: "Evento", relation: "Relazione", insight: "Insight" } as Record<string, string>,
  kindsPlural: { object: "Oggetti", event: "Eventi", relation: "Relazioni", insight: "Insight" } as Record<string, string>,
  trailEmpty: "Nessun fuoco: seleziona un elemento in qualunque vista",
  trailBack: "Passo precedente",
  trailForward: "Passo successivo",
  trailSave: "Salva",
  trailSaved: "Salvato",
  trailExport: "Esporta JSON",
  trailImport: "Importa",
  trailList: "Trail salvati",
  trailMissing: "non più presente",
  trailName: "Nome del trail",
  trailNew: "Nuovo trail",
  trailPath: "Percorso",
  trailSteps: (n: number) => `${n} ${n === 1 ? "passo" : "passi"}`,
  m: {
    mostly: (type: string) => `soprattutto ${type.toLowerCase()}`,
    back: "Indietro",
    path: "Percorso",
    more: "Altro",
    filters: "Filtri",
    filtersActive: (n: number) => `Filtri · ${n} ${n === 1 ? "attivo" : "attivi"}`,
    info: "Informazioni",
    close: "Chiudi",
    tapHint: "Tocca un elemento per vedere a cosa è collegato",
    found: (n: number | null) => `Cosa sta succedendo${n != null ? ` (${n.toLocaleString("it-IT")})` : ""}`,
    openAll: "Tutte le connessioni e i dettagli",
    collapse: "Riduci",
    connCount: (n: number) => (n ? `${n} ${n === 1 ? "connessione" : "connessioni"}` : "nessuna connessione"),
    sheetHandle: "Apri o riduci la scheda dell'elemento",
    mapFloor: "Confidenza minima sulla mappa",
    mapFloorNote: "Vale per elementi ed eventi della mappa. Gli insight non usano questa soglia: la loro confidenza misura il supporto di un'associazione, su un'altra scala.",
    scopeConf: (v: string) => `In tutte le viste: confidenza ≥ ${v}`,
    remove: "Rimuovi",
    resetFilters: "Rimuovi tutti i filtri",
    density: "Le zone più chiare contengono più elementi: avvicinati per vederli",
  },
  period: {
    label: "Periodo",
    chip: (name: string) => `Periodo · ${name}`,
    title: "Che periodo stai guardando",
    presets: "Scegli",
    year: "Un anno",
    custom: "Personalizzato",
    from: "da",
    to: "a",
    apply: "Applica",
    note: "Il periodo vale per eventi e insight; paesi, aeroporti e gli altri elementi senza data restano sempre visibili. I periodi sono a mesi interi, come li conta la mappa.",
    fresh: (day: string) => `Dati aggiornati al ${day}`,
    published: (utc: string) => `snapshot pubblicato il ${utc} UTC`,
    outside: (name: string) => `Fuori dal periodo osservato · ${name}`,
    goYear: (y: number) => `Vai al ${y}`,
    outsideShort: "fuori dal periodo osservato",
    observedWith: (what: string) => `Osservato con: ${what}`,
    applyStep: "Applica",
    legend: (name: string) => `Eventi e insight: ${name}`,
    always: "elementi senza data sempre visibili",
  },
  reset: "Ripristina filtri",
  // an image kept current by its source, opened only on request (Phase 3B · block 1); LIVE only for real video
  media: {
    kinds: { current_image: "Immagine attuale", live_video: "Video live", static_reference: "Immagine di riferimento" } as Record<string, string>,
    notLive: "immagine fissa aggiornata dalla fonte, non un video",
    refresh: (m: string) => `la fonte la aggiorna circa ogni ${m} min`,
    open: "Mostra l'immagine attuale",
    reload: "Ricarica",
    loaded: (t: string) => `Caricata alle ${t} direttamente dalla fonte`,
    observed: (t: string) => `ultima immagine dichiarata dalla fonte: ${t}`,
    off: "La fonte segnala questa camera come non in servizio.",
    error: "Immagine non disponibile in questo momento.",
    privacy: "NEXUM non conserva né analizza l'immagine: la chiede alla fonte solo quando la apri.",
    credit: "Credito",
    status: { current_snapshot: "IMMAGINE CORRENTE", stale: "NON DISPONIBILE · immagine ferma alla fonte", offline: "NON DISPONIBILE · fuori servizio",
      live_stream: "LIVE", link_only: "SOLO COLLEGAMENTO", unknown: "STATO NON NOTO" } as Record<string, string>,
    placeTitle: "Webcam nelle vicinanze",
    placeNote: (km: number) => `Webcam pubbliche entro ${km} km. L'immagine si carica solo quando apri la webcam.`,
    placeNone: (km: number) => `Nessuna webcam pubblica registrata entro ${km} km.`,
    placeMore: (n: number, shown: number) => `In tutto ${n.toLocaleString("it-IT")}: qui le ${shown} più vicine (tutte sulla mappa).`,
    stale: "L'ultima immagine dichiarata dalla fonte è vecchia: la camera non mostra la situazione attuale.",
    linkTitle: "Webcam del gestore",
    nearTitle: "Webcam pubbliche vicine (evento recente)",
    nearNote: (km: number, days: number) => `Entro ${km} km da un evento degli ultimi ${days} giorni di dati. Una webcam vicina non mostra necessariamente l'evento: la sua immagine è quella attuale.`,
    linkOpen: "APRI WEBCAM",
    linkNote: "Si apre la pagina originale del gestore. NEXUM non mostra anteprime di questa webcam: il gestore non consente di riprodurne le immagini altrove.",
  },
  facts: { title: "Dati della fonte", source: "Fonte", ident: "Identificativo" },
  rates: {
    title: "Tariffa",
    rate: "Tariffa per km",
    components: "Componenti",
    amount: (n: string, km: string) => `Importo per tutte le ${n} tratte (${km} km)`,
    segments: (n: number) => `Tratte (${n})`,
    note: "Ogni tratta percorsa anche solo in parte si paga per intero; importo = lunghezza × tariffa, arrotondato al centesimo per tratta. NEXUM non calcola percorsi.",
    validity: "Validità", rounding: "Arrotondamento", legal: "Riferimento",
    loading: "Carico la tariffa…",
  },
  gov: {
    title: "Governo e vertici dello Stato",
    office: "Ufficio",
    terms: "Mandati",
    since: (d: string) => `dal ${d}`,
    range: (a: string, b: string) => `${a} – ${b}`,
    noEnd: "fine non registrata dalla fonte",
    none: "Nessun titolare attuale documentato dalla fonte.",
    conflict: "La fonte è contraddittoria: più titolari attuali. NEXUM li mostra tutti e non sceglie.",
    collegial: "Ufficio collegiale: sono mostrati i membri con l'ultima data d'inizio registrata; altri membri possono mancare.",
    history: (n: number) => `Storia dell'ufficio dal 1990 (${n})`,
    status: { current: "in carica", ended: "concluso", superseded: "superato da un titolare successivo", conflict: "in conflitto", undated: "senza data d'inizio" } as Record<string, string>,
    statement: "Enunciato", refs: "Riferimenti", rank: "Rango", retrieved: "Recuperato il", jurisdiction: "Giurisdizione", flags: "Segnalazioni",
    source: "Fonte: Wikidata (CC0)",
    rectify: "Segnala una correzione",
    rectifyUrl: "https://github.com/pezzaliapp/NEXUM/issues",
    privacy: "Solo fatti di ruolo pubblico (ufficio e date), con la loro evidenza. Nessuna foto né dato personale.",
    during: "Durante il mandato di",
    duringPre: "L'evento è avvenuto durante il mandato di ",
    duringPost: (office: string, range: string) => ` (${office}, ${range}).`,
    duringAmbiguous: (office: string) => `${office}: la fonte indica più titolari per questa data; NEXUM non sceglie.`,
    duringNote: "Contesto temporale: non indica alcuna causa né responsabilità.",
    personTerms: "Incarichi apicali documentati",
    personLine: (office: string, range: string) => `${office}: ${range}`,
  },
  place: {
    nav: { overview: "Panoramica", vivere: "Vivere", prezzi: "Prezzi", abitazione: "Abitazione", energia: "Energia",
      infrastrutture: "Infrastrutture", economia: "Economia", popolazione: "Popolazione", gov: "Governo", opinione: "Opinione",
      sicurezza: "Sicurezza", eventi: "Eventi", osserva: "Osserva", sources: "Fonti",
      opinion: "Opinione", reality: "Realtà", events: "Eventi", places: "Luoghi", connections: "Connessioni" } as Record<string, string>,
    people: "Popolazione",
    living: "Vivere e prezzi",
    livingOnly: "Vivere",
    prices: "Prezzi",
    energy: "Energia",
    economy: "Economia",
    security: "Sicurezza",
    observe: "Osserva",
    mix: (y: string) => `Mix elettrico ${y}`,
    gasFrom: "Gas da",
    noSalary: "Stipendi: nessuna fonte aperta con una definizione verificabile per questo Paese (il PIL pro capite non è uno stipendio).",
    limitedSalary: "Stipendi: solo dati con limiti metodologici (in Vivere, sezione apposita).",
    conflictCount: (n: number) => `${n.toLocaleString("it-IT")} eventi di violenza organizzata documentati (UCDP)`,
    securityNote: (p: string) => `Violenza organizzata letale documentata da UCDP a ${p} (eventi con almeno 5 morti stimati). Dati preliminari, con 3–7 settimane di ritardo: non è una situazione in tempo reale né una previsione.`,
    observeNote: (n: number) => n > 0 ? `Immagini satellitari su richiesta · ${n.toLocaleString("it-IT")} webcam pubbliche` : "Immagini satellitari su richiesta · nessuna webcam pubblica con licenza aperta",
    noWebcams: "Nessuna webcam pubblica con licenza aperta registrata qui.",
    observeImagery: "Immagini satellitari su richiesta",
    webcamsInNexum: (n: number) => n > 0 ? `${n.toLocaleString("it-IT")} webcam disponibili in NEXUM (non sono tutte le webcam del Paese)` : "Nessuna webcam disponibile in NEXUM",
    coverage: "copertura delle fonti:",
    unspecified: "non indicato",
    navLabel: "Sezioni",
    open: (what: string) => `${what} →`,
    gov: "Governo e vertici dello Stato",
    opinion: "Opinione pubblica",
    pairs: "Realtà e percezione",
    reality: "Dati ufficiali",
    events: "Eventi recenti",
    places: "Luoghi e infrastrutture",
    since: (d: string) => `dal ${d}`,
    retrieved: (d: string) => `recuperato il ${d}`,
    official: "dato ufficiale", perceived: "percezione",
    noHolder: "nessun titolare attuale documentato",
    exploreAll: (n: number, what: string) => `Esplora ${what.toLowerCase()} (${n})`,
    eventsCount: (n: number) => `${n.toLocaleString("it-IT")} eventi collegati`,
    showOnMap: "Mostra sulla mappa",
    exploreOnMap: "Esplora sulla mappa",
    onMapNote: "La mappa mostra solo questa categoria: «Ripristina filtri» riporta tutto.",
    showLinks: "Mostra i collegamenti sulla mappa",
    hideLinks: "Nascondi i collegamenti dalla mappa",
    fresh: { current: "attuale", recent: "recente", historical: "storico" } as Record<string, string>,
    // the order in which the overview reads the topics of public opinion (the first ones available, at most three lines)
    opinionOrder: ["direzione", "economia", "istituzioni", "futuro personale", "famiglie", "prezzi", "lavoro", "preoccupazioni"],
    noCause: "contesto temporale, non causa",
  },
  zones: {
    title: "Zone con violenza documentata (UCDP)",
    window: (a: string, b: string, n: number) => `${n} giorni di dati UCDP: dal ${a} al ${b} (dati preliminari, con 3–7 settimane di ritardo; non è una situazione in tempo reale)`,
    none: "Nessuna zona rossa o arancione nel periodo: nessun evento letale documentato che soddisfi le regole (assenza di dati non significa assenza di rischio).",
    red: "ROSSO · attività violenta documentata",
    orange: "ARANCIONE · esposizione documentata (attore statale estero)",
    summary: (n: number, d: number, a: string, b: string) => `${n} eventi letali, ${d.toLocaleString("it-IT")} morti (stima migliore) · ${a} – ${b}`,
    why: "Perché questa zona?",
    rule: "Regola", period: "Periodo", area: "Area disegnata", source: "Fonte",
    cells: (n: number) => `${n} ${n === 1 ? "cella" : "celle"} di 0,5° (griglia PRIO-GRID) che contengono gli eventi; non l'intera unità amministrativa`,
    sourceText: (f: string[]) => `UCDP Candidate Events Dataset (${f.join(", ")}), CC BY 4.0 — eventi con ≥ 1 morto stimato, descrizione chiara, data al giorno o alla settimana, luogo almeno alla provincia`,
    deaths: (b: number, l: number, h: number) => `${b} morti (stima migliore; da ${l} a ${h})`,
    foreign: "attore statale estero",
    open: "apri l'evento",
    more: (n: number) => `e altri ${n} eventi`,
    showMap: "Mostra le zone sulla mappa", hideMap: "Nascondi le zone dalla mappa",
    note: "Le zone sono calcolate da NEXUM con regole dichiarate sui dati UCDP: nessuna previsione; la sola vicinanza a una zona non colora nulla.",
  },
  sat: {
    title: "Immagini satellitari",
    what: (p: string) => `Immagini satellitari di ${p}, chieste ai servizi pubblici solo quando le apri (nessuna copia, nessun archivio).`,
    p: {
      mtgDay: "Meteosat · colori reali (ogni 10 min)", mtgNight: "Meteosat · infrarosso (ogni 10 min, di notte)",
      himawariDay: "Himawari · visibile (ogni 10 min)", himawariNight: "Himawari · infrarosso (ogni 10 min, di notte)",
      goes: (east: boolean) => `GOES ${east ? "Est" : "Ovest"} · GeoColor (ogni 10 min)`,
      viirs: "Foto del giorno · colori reali (VIIRS)", hls: "Dettaglio 30 m (Landsat/Sentinel-2)",
    },
    cls: { nrt: "QUASI IN TEMPO REALE", latest: "ULTIMA DISPONIBILE", historical: "STORICA" } as Record<string, string>,
    acquired: (t: string) => `acquisita ${t}`,
    today: "acquisita oggi (UTC)", yesterday: "acquisita ieri (UTC)",
    ageMin: (n: number) => `${n} min fa`, ageH: (n: number) => `${n} ore fa`, ageD: (n: number) => `${n} giorni fa`,
    res: (r: string) => `risoluzione nominale ${r}`,
    cloud: (n: number) => `nuvolosità ${n}%`,
    loading: "Chiedo l'immagine…",
    none: "Nessuna immagine disponibile per questo momento e questo luogo (il servizio non ha dati: nessuna immagine vuota viene mostrata).",
    timeline: "Momento dell'immagine",
    latest: "Ultima",
    note: "Mai «live»: geostazionari con 15–50 minuti di ritardo, foto del giorno a un passaggio al giorno, dettaglio 30 m ogni alcuni giorni (nubi permettendo). Non si vedono persone né veicoli.",
  },
  cmp: {
    title: "Confronta i Paesi",
    note: (n: number) => `${n} Paesi su 193 hanno questo dato. Ordine alfabetico: nessuna classifica. Tocca un Paese per fissarlo in alto e confrontarlo.`,
    filter: "Cerca un Paese…",
    caveat: "Stessa fonte e stessa definizione per tutti i Paesi; anni diversi sono indicati accanto al valore. Per i salari le definizioni nazionali possono differire.",
    notComparable: "NON CONFRONTABILE: la fonte usa definizioni diverse da Paese a Paese (dato ambiguo). I valori sono elencati solo come riferimento, non per un confronto.",
  },
  ind: {
    formula: (what: string, unit: string, pop: string) => `${what} (${unit}) ÷ ${pop.toLowerCase()} dello stesso anno — calcolato da NEXUM`,
    pcGeneration: "Produzione di elettricità per abitante",
    pcFrom: (label: string) => `${label.replace("Produzione elettrica da ", "Elettricità da ")} per abitante`,
    pcConsumption: "Consumo netto di elettricità per abitante (EIA)",
    pcDemand: "Domanda di elettricità per abitante",
    pcEnergy: "Consumo di energia primaria per abitante",
    nexum: "Calcolato da NEXUM",
    limitedTitle: (n: number) => `Dati disponibili con limiti metodologici (${n})`,
    limitedNote: "Valori pubblicati dalla fonte senza una definizione verificabile per questo Paese (lordo o netto, tipo di indagine, mese ricavato dall'anno): restano consultabili con il loro limite, ma non sono la risposta della sezione e non si confrontano tra Paesi.",
    buyTopic: "potere d'acquisto",
    buyKwh: "Elettricità per la casa acquistabile con un mese di stipendio netto",
    buyKwhWhat: "prezzo medio dell'elettricità per le famiglie dello stesso anno (media dei due semestri, tasse incluse)",
    buyPetrol: "Benzina acquistabile con un mese di stipendio netto",
    buyPetrolWhat: "prezzo medio della benzina dello stesso anno (media dei prezzi settimanali, tasse incluse)",
    buyFormula: (net: string, what: string) => `${net} ÷ 12 ÷ ${what}; stessa valuta (EUR), stesso anno — calcolato da NEXUM`,
    nexumAttr: "Calcolato da NEXUM dividendo due valori pubblicati dalle fonti indicate, per lo stesso anno",
    gapsTitle: (place: string) => `Dati non disponibili per ${place}`,
    noGaps: "Nessuna lacuna: ogni indicatore di questa sezione ha un valore.",
    notAvailable: "dato non disponibile",
    coverage: (n: number) => `la fonte copre ${n} Paesi su 193`,
    flowOrder: <string[]>["imports_gas_from|out", "imports_gas_from|in", "imports_crude_from|out", "imports_crude_from|in",
      "imports_electricity_from|out", "exports_electricity_to|out", "imports_electricity_from|in", "exports_electricity_to|in"],
    flowTitle: (type: string, dir: string) => ({
      "imports_gas_from|out": "Da dove arriva il gas", "imports_gas_from|in": "Gas verso Paesi europei (dichiarato dagli importatori)",
      "imports_crude_from|out": "Da dove arriva il petrolio greggio", "imports_crude_from|in": "Greggio verso Paesi europei (dichiarato dagli importatori)",
      "imports_electricity_from|out": "Elettricità importata da", "exports_electricity_to|out": "Elettricità esportata verso",
      "imports_electricity_from|in": "Elettricità verso Paesi europei (dichiarata dagli importatori)",
      "exports_electricity_to|in": "Elettricità da Paesi europei (dichiarata dagli esportatori)",
    } as Record<string, string>)[`${type}|${dir}`] ?? type,
    declaredBy: (p: string) => `dichiarato da ${p}`,
    declaredByPartners: "dichiarato dai Paesi partner",
    flowEvidence: "perché?",
    more: (n: number) => `e altri ${n} partner`,
    noFlows: (p: string) => `Nessun dato aperto sui Paesi di provenienza dell'energia di ${p}: le fonti con licenza aperta coprono solo i Paesi europei (Eurostat). Restano i totali senza partner.`,
  },
  explore: {
    suggestions: "Con più dati",
    none: "Nessun risultato",
    open: "Apri",
  },
  changes: {
    title: "Cambiamenti documentati",
    note: "Solo cambiamenti registrati dalle fonti: nuovi titolari di un ufficio apicale e nuove rilevazioni o pubblicazioni.",
    tenure: (role: string) => `Nuovo titolare · ${role}`,
    release: (group: string) => `Nuovi dati · ${group}`,
    inN: (n: number, many: string) => `${n} ${n === 1 ? "elemento" : many}`,
  },
  obs: {
    opinion: "Opinione pubblica",
    reality: "Realtà · dati ufficiali",
    pairs: "Realtà e percezione",
    pairNote: "Due misure diverse, una accanto all'altra: NEXUM non le combina in un indice e non giudica chi ha ragione.",
    official: "Dato ufficiale",
    perceived: "Percezione (sondaggio)",
    loading: "Carico le osservazioni…",
    value: "Valore", when: "Periodo", fieldwork: "Rilevazione", source: "Fonte",
    question: "Domanda", answer: "Risposta", population: "Popolazione", sample: "Campione", method: "Metodo",
    seasonal: "Stagionalità", dataset: "Pubblicazione", definition: "Definizione", flags: "Note della fonte",
    moe: "Margine d'errore", moeText: (x: string) => `±${x} punti (95%, stimato da NEXUM dal campione, effetto del disegno 2)`,
    moeBalance: (x: string) => `±${x} punti sul saldo (95%, dall'errore standard al campione nominale, effetto del disegno 2)`,
    interviews: (n: string) => `${n} interviste`,
    history: "Valori precedenti",
    nature: "Natura del dato", formula: "Calcolo", coverage: "Copertura della fonte", note: "Nota",
    natures: { observed: "osservato", reported: "pubblicato dalla fonte (statistiche nazionali)", estimated: "stima della fonte",
      modelled: "stima modellata dalla fonte", derived: "calcolato da NEXUM",
      ambiguous: "AMBIGUO: la definizione non è verificabile (lordo/netto, calcolo del mensile, tipo d'indagine): non confrontabile tra Paesi" } as Record<string, string>,
    natureShort: { estimated: "stima", modelled: "modellato", ambiguous: "ambiguo" } as Record<string, string>,
    coverageOf: (n: number) => `${n} Paesi su 193 hanno questo dato`,
    derived: "calcolato da NEXUM",
    staleTag: "dato vecchio",
    anomalyTag: "anomalia nella fonte",
    evidence: "Apri il record della fonte",
    up: "in aumento", down: "in calo", stable: "stabile entro il margine d'errore",
    none: "variazione non valutabile (manca l'errore campionario)",
    single: "una sola rilevazione: nessun confronto",
    vs: (p: string) => `rispetto a ${p}`,
    beyond: (d: string, t: string) => `${d} punti, oltre la soglia di ±${t}`,
    within: (d: string, t: string) => `${d} punti, entro la soglia di ±${t}`,
    change: (d: string, p: string) => `${d} rispetto a ${p}`,
    noChange: (p: string) => `invariato rispetto a ${p}`,
    dirNote: "Una freccia compare solo per la stessa domanda, sulla stessa popolazione, quando la differenza supera l'errore campionario. Non è una previsione.",
    estimate: "stima",
    measured: "Misurato", result: "Risultato", changeLabel: "Variazione",
    record: "Risultati misurati in questa rilevazione", recordSeries: "Risultato misurato",
    area: "Ambito", currency: "Valuta", withoutTaxes: "Prezzo senza tasse", taxSince: (d: string) => `in vigore dal ${d}`,
    more: (n: number) => `Altre ${n}`,
    units: { balance: "saldo", share: "%", rate: "%", bn: "miliardi", mn: "milioni" } as Record<string, string>,
  },
  filters: {
    events: "Eventi",
    places: "Luoghi e infrastrutture",
    connections: "Connessioni NEXUM",
    showConnections: "Mostra le connessioni trovate da NEXUM",
    advanced: "Avanzate",
    rules: "Connessioni, una regola alla volta",
    empty: "Categorie senza risultati nel periodo",
    onMap: "Sulla mappa",
    zones: "Zone con violenza documentata (UCDP, 90 giorni)",
    all: "Tutto",
    none: "Nessuno",
    byDefault: "Ripristina",
    defaultTitle: "Torna alla mappa iniziale di NEXUM: solo le città (confini e cartografia restano sempre)",
  },
  hl: {
    title: "Cosa sta succedendo",
    found: "Cosa ha trovato NEXUM",
    domains: "Domini attivi · eventi negli ultimi 12 mesi dei dati",
    onlyThis: "Mostra solo questo dominio (un filtro: Ripristina filtri lo toglie)",
    recent: "Ora · gli eventi rilevanti più recenti",
    strongest: "Eventi rilevanti · i più forti negli ultimi 12 mesi",
    connections: "Connessioni trovate da NEXUM · le più recenti",
    all: "Tutto quello che sta succedendo",
    feed: "Cosa sta succedendo",
  },
  home: "Esplora",
  homeTitle: "Chiudi il fuoco e torna al mondo (i filtri restano)",
  resetTitle: "Torna al periodo e ai filtri iniziali (il fuoco resta)",
  hidden: {
    tag: "esclusa dai filtri",
    count: (n: number) => `${n} ${n === 1 ? "connessione nascosta" : "connessioni nascoste"} dai filtri`,
    show: "Mostra",
    ignored: "Filtri ignorati per questo elemento",
    reapply: "Riapplica",
  },
  conn: {
    title: "Connessioni trovate da NEXUM",
    geo: "Contesto geografico",
    context: "Contesto · non sono connessioni",
    sameTerritory: (n: number, via: string | null) => `${n.toLocaleString("it-IT")} eventi che coinvolgono anche ${via ?? "lo stesso elemento"}`,
    sameTerritoryNote: "Hanno in comune soltanto questo elemento: è contesto, non una correlazione.",
    nearby: (n: number) => `${n.toLocaleString("it-IT")} elementi entro 100 km`,
    nearbyNote: "Vicinanza geografica: non è una connessione registrata.",
    all: (n: number) => `Tutte le connessioni (${n})`,
    fewer: "Mostra meno",
    andMore: (n: number) => `e altri ${n.toLocaleString("it-IT")}`,
    see: "Osserva in",
    ruleAssociation: "associazione trovata da una regola",
    ruleContext: "contesto trovato da una regola",
  },
  legend: {
    hint: "Tocca un elemento: vedi a cosa è collegato e perché",
    insight: "insight",
    period: (a: string, b: string) => `${a}–${b}`,
    groups: "le zone più chiare contengono più elementi: avvicinati",
    daylight: "Giorno e notte: calcolati dall'ora UTC corrente",
    lights: "Luci notturne · NASA/VIIRS · composito di riferimento (2016)",
    lightsCredit: "Luci notturne: NASA Earth Observatory, Black Marble 2016 (VIIRS Day/Night Band), composito delle notti serene del 2016 — immagine di riferimento, non osservazione in tempo reale",
    kinds: { event: "eventi", object: "luoghi e infrastrutture", insight: "connessioni trovate da NEXUM" } as Record<string, string>,
  },
  web: {
    snapshot: "Snapshot",
    builtAt: (utc: string, age: string) => `dati del ${utc} UTC · ${age}`,
    newer: "È stato pubblicato un aggiornamento del mondo.",
    reload: "Ricarica",
    trailLocal: "La trail è salvata solo in questo browser: esporta il JSON per conservarla altrove.",
    persisted: "Archivio del browser protetto dalla pulizia automatica.",
    notPersisted: "Il browser può cancellare questo archivio: esporta il JSON per conservarlo.",
    safari7: "Safari cancella i dati del sito dopo 7 giorni senza visite: aggiungi NEXUM alla schermata Home oppure esporta il JSON.",
  },
  railTitle: "Livelli e filtri",
  railTypes: "Tipi visibili",
  railAll: "tutti",
  railNone: "nessuno",
  railConfidence: "Confidenza minima",
  railSources: "Fonti",
  railTime: "Finestra temporale",
  railTimeAll: "tutto il periodo",
  railTimeClear: "Rimuovi la finestra",
  confBands: ["qualsiasi", "≥ 0,50 (media)", "≥ 0,80 (forte)"],
  bandLabel: ["supporto debole", "supporto medio", "supporto forte"],
  worldSummary: "Il mondo visibile",
  counts: "Conteggi",
  relevantInsights: "Connessioni trovate da NEXUM nell'area visibile",
  relevantInsightsNote: "Associazioni e contesti calcolati da regole su questi dati: tocca un elemento o chiedi Perché?",
  moreInsights: "altri insight",
  sources: "Fonti",
  health: { ok: "attiva", degraded: "degradata", suspended: "sospesa" } as Record<string, string>,
  lastUpdate: "ultimo aggiornamento",
  noGeometryNotice: (n: number) =>
    `${n.toLocaleString("it-IT")} elementi senza posizione geografica: li trovi in Grafo, Tempo e Cerca`,
  mapNotApplicable: (n: number) =>
    `Questo mondo non contiene elementi con geometria (0 su ${n.toLocaleString("it-IT")}). La mappa non si applica: usa Grafo, Tempo e Cerca.`,
  aggregated: (_level: number, n: number) => `${n.toLocaleString("it-IT")} gruppi · avvicinati per i singoli elementi`,
  individual: (n: number, total: number) =>
    `${n.toLocaleString("it-IT")} elementi${total > n ? ` su ${total.toLocaleString("it-IT")}` : ""}`,
  truncated: "mostrati i più rilevanti",
  inCell: "In quest'area, insieme ad altri elementi",
  inBucket: "nel periodo evidenziato",
  inAggregate: "raggruppato con altri elementi dello stesso tipo",
  notOnMap: "Non ha una posizione geografica: non compare sulla mappa",
  notInTime: "non ha un tempo proprio",
  outsideScope: "Non è nell'area visibile",
  excludedByFilters: "Escluso dai filtri attivi",
  focusDespiteFilters: "Mostrato perché è il fuoco: i filtri nascondono gli elementi simili",
  focusOutsidePeriod: "Mostrato perché è il fuoco: è fuori dal periodo osservato",
  zoomIn: "Avvicinati",
  showOnMap: "Mostra",
  loading: "caricamento…",
  error: "errore",
  retry: "Riprova",
  busy: "Servizio occupato: riprovo tra poco",
  deadline: "La richiesta ha superato il tempo massimo: restringi area, finestra o filtri",
  sections: {
    identity: "Identità", type: "Tipo", properties: "Proprietà", sources: "Fonti", evidence: "Evidenze",
    relations: "Relazioni", relatedObjects: "Oggetti correlati", relatedEvents: "Eventi correlati",
    timeline: "Timeline", geography: "Geografia", insights: "Insight", provenance: "Provenienza",
    members: "Membri", participants: "Partecipanti",
    technical: "Dettagli tecnici · identità, tipo, proprietà, membri, provenienza",
  },
  copy: "Copia l'ID",
  copied: "ID copiato",
  conflicts: (n: number) => `${n} valori da fonti diverse`,
  independentOf: (i: number, n: number) => `${i} fonti indipendenti su ${n} evidenze`,
  geographyNA: "Non applicabile: l'elemento non ha geometria",
  contains: "si trova in",
  nearby: (n: number) => `${n} elementi entro 100 km`,
  more: (n: number) => `altri ${n.toLocaleString("it-IT")}`,
  showMore: "Mostra altri",
  none: "nessuno",
  prev: "precedente",
  next: "successivo",
  openFocus: "Metti a fuoco",
  why: "Perché?",
  whyTitle: "Perché questa connessione?",
  whyBack: "Torna all'elemento",
  causal: "Associazione: non indica un rapporto di causa.",
  whyRule: "Regola",
  whyRuleActive: "attiva in questo mondo",
  whyRuleNewer: (v: string) => `esiste una versione più recente (${v})`,
  whyCandidates: "Candidati considerati",
  whyGrouping: "Raggruppamento",
  whyRepresentative: "Rappresentante",
  whyRejected: "Scartati",
  whyConfidence: "Confidenza e fattori",
  whyEvidence: "Evidenze",
  whyIndependent: "Fonti indipendenti",
  whyComponents: "Componenti",
  whyUsedBy: "Usata da",
  whyLimitations: "Limiti noti",
  whyMembers: "Membri del pattern",
  whyLinked: "Elementi collegati",
  whyFound: "Connessione trovata da NEXUM",
  whyTechnical: "Dettagli tecnici · regola, soglie, confidenza numerica",
  notRecorded: "non registrato",
  notApplicable: "non applicabile",
  recomputedOk: (v: string) => `ricalcolato ${v} = memorizzato ✓`,
  recomputedKo: (a: string, b: string) => `ricalcolato ${a} ≠ memorizzato ${b}`,
  groupSupportBy: (v: string) => `supporto del gruppo ${v} fornito da`,
  notIndependent: "non indipendente",
  derivation: "Derivazione",
  explanationGenerated: "enunciato generato dai riferimenti",
  rawRecord: "Record originale",
  rawOpen: "Mostra il record originale",
  rawHide: "Nascondi il record",
  licence: "Licenza",
  fetched: "acquisito",
  graph: {
    depth: "Profondità",
    budgetLabel: "Nodi max",
    phoneLimits: "prof. 1 · max 100",
    filters: "Filtri",
    omitted: (n: number) => `${n} nodi omessi per rispettare il budget`,
    nodes: (n: number, e: number) => `${n} nodi · ${e} archi`,
    budget: (n: number, e: number) => `budget ${n} / ${e}`,
    aggregate: (n: number, t: string) => `+${n.toLocaleString("it-IT")} ${t}`,
    nextPage: "Pagina successiva",
    pageOf: (a: number, b: number) => `pagina ${a} di ${b}`,
    pathTo: "Percorso verso il secondo elemento",
    pathHint: "Maiusc+clic su un secondo elemento per il percorso",
    pathNone: "Nessun percorso entro 4 passaggi",
    pathFound: (h: number) => `Percorso di ${h} passaggi`,
    keepPath: "Tieni solo il percorso",
    recenter: "Ricentra",
    clear: "Pulisci",
    expand: "Espandi",
    tooMany: "Espansione oltre il limite di 2.000 nodi: filtra per tipo o finestra, o apri un nodo aggregato",
    noFocus: "Seleziona un elemento per vederne le relazioni",
    noConnections: "Nessuna connessione trovata per questo elemento.",
    options: "Opzioni",
    connected: (n: number) => `${n} ${n === 1 ? "elemento collegato" : "elementi collegati"}`,
    edgeKinds: { relation: "relazione", participation: "partecipazione", insight_member: "membro di insight",
      hypothesis: "ipotesi" } as Record<string, string>,
    layout: "layout deterministico",
    insightsToggle: "Insight",
  },
  time: {
    bucket: { hour: "ora", day: "giorno", week: "settimana", month: "mese", year: "anno" } as Record<string, string>,
    focusTrack: "elemento",
    relatedTrack: "collegati",
    density: "tutti gli eventi",
    noDated: (label: string) => `Nessun evento datato collegato a ${label}: le barre mostrano tutti gli eventi del mondo`,
    brushHint: "Trascina per scegliere un periodo (a mesi interi) · rotella per lo zoom",
    reset: "Mostra tutti gli anni",
    noTime: "Nessun evento nel mondo",
    around: (n: number, label: string, a: string, b: string) =>
      `${n} ${n === 1 ? "evento datato collegato" : "eventi datati collegati"} a ${label}${n ? `, ${a === b ? `il ${a}` : `dal ${a} al ${b}`}` : ""}`,
    noneAround: (label: string) => `Nessun evento datato collegato a ${label}${label.endsWith(".") ? "" : "."}`,
    world: "Tocca un elemento per vedere cosa è successo intorno e quando.",
    band: "Tutti gli eventi del mondo, per anno",
    list: "In ordine di tempo",
    focusSelf: "l'elemento",
    options: "Periodo e granularità",
    periodTitle: "Periodo",
    window: "Finestra attiva",
    useSpan: "Limita le viste a questo periodo",
    outside: "fuori dal periodo osservato",
    granularity: "Granularità",
    contextTitle: (n: number) => `Contesto · ${n} eventi che coinvolgono lo stesso elemento`,
  },
  status: {
    version: "versione del mondo",
    sourcesOk: (a: number, b: number) => `fonti ${a}/${b}`,
    data: "Dati",
  },
  mobileBack: "Indietro",
  openRail: "Filtri",
  closePanel: "Chiudi",
  about: "Informazioni",
  keyboard: "Tastiera: / cerca · [ ] trail · W perché · M mappa · G grafo · Esc chiudi",
} as const;
