// Every user-visible string of the workspace lives here (W22 scans this catalogue for causal or
// probabilistic wording; new languages can be added later without touching the views).

export const S = {
  appName: "NEXUM",
  motto: "ONE OBJECT. MANY RELATIONS. ONE TIMELINE.",
  searchPlaceholder: "Cerca oggetti, eventi, insight o incolla un ID…",
  searchTooShort: "Almeno 2 caratteri",
  searchNone: "Nessun risultato nello scope",
  searchUnranked: (n: number | null) =>
    `Risultati non ordinati per rilevanza${n != null ? ` (circa ${n})` : ""}: affina la ricerca`,
  views: { map: "Mappa", graph: "Grafo", split: "Mappa + Grafo", time: "Tempo", search: "Cerca", focus: "Fuoco" },
  kinds: { object: "Oggetto", event: "Evento", relation: "Relazione", insight: "Insight" } as Record<string, string>,
  kindsPlural: { object: "Oggetti", event: "Eventi", relation: "Relazioni", insight: "Insight" } as Record<string, string>,
  trailEmpty: "Nessun fuoco: seleziona un elemento in qualunque vista",
  trailBack: "Passo precedente",
  trailForward: "Passo successivo",
  trailSave: "Salva",
  trailSaved: "Salvato",
  trailExport: "Esporta JSON",
  trailImport: "Importa",
  trailList: "Trail salvati",
  trailMissing: "non più presente",
  trailName: "Nome del trail",
  trailNew: "Nuovo trail",
  railTitle: "Livelli e filtri",
  railTypes: "Tipi visibili",
  railAll: "tutti",
  railNone: "nessuno",
  railConfidence: "Confidenza minima",
  railSources: "Fonti",
  railTime: "Finestra temporale",
  railTimeAll: "tutto il periodo",
  railTimeClear: "Rimuovi la finestra",
  confBands: ["qualsiasi", "≥ 0,50 (media)", "≥ 0,80 (forte)"],
  bandLabel: ["supporto debole", "supporto medio", "supporto forte"],
  worldSummary: "Quadro dello scope",
  counts: "Conteggi",
  relevantInsights: "Insight rilevanti",
  moreInsights: "altri insight",
  sources: "Fonti",
  health: { ok: "attiva", degraded: "degradata", suspended: "sospesa" } as Record<string, string>,
  lastUpdate: "ultimo aggiornamento",
  noGeometryNotice: (n: number) =>
    `${n.toLocaleString("it-IT")} elementi dello scope non hanno geometria: sono in Grafo, Tempo, Cerca e Insight`,
  mapNotApplicable: (n: number) =>
    `Questo mondo non contiene elementi con geometria (0 su ${n.toLocaleString("it-IT")}). La mappa non si applica: usa Grafo, Tempo e Cerca.`,
  aggregated: (level: number, n: number) => `aggregato · livello ${level} · ${n.toLocaleString("it-IT")} celle`,
  individual: (n: number, total: number) =>
    `${n.toLocaleString("it-IT")} elementi${total > n ? ` su ${total.toLocaleString("it-IT")}` : ""}`,
  truncated: "troncato al budget",
  inCell: "dentro una cella aggregata",
  inBucket: "dentro un intervallo aggregato",
  inAggregate: "dentro un nodo aggregato",
  notOnMap: "non ha geometria: non compare sulla mappa",
  notInTime: "non ha un tempo proprio",
  outsideScope: "fuori dallo scope corrente",
  loading: "caricamento…",
  error: "errore",
  retry: "Riprova",
  busy: "Servizio occupato: riprovo tra poco",
  deadline: "La richiesta ha superato il tempo massimo: restringi area, finestra o filtri",
  sections: {
    identity: "Identità", type: "Tipo", properties: "Proprietà", sources: "Fonti", evidence: "Evidenze",
    relations: "Relazioni", relatedObjects: "Oggetti correlati", relatedEvents: "Eventi correlati",
    timeline: "Timeline", geography: "Geografia", insights: "Insight", provenance: "Provenienza",
    members: "Membri", participants: "Partecipanti",
  },
  copy: "Copia l'ID",
  copied: "ID copiato",
  conflicts: (n: number) => `${n} valori da fonti diverse`,
  independentOf: (i: number, n: number) => `${i} fonti indipendenti su ${n} evidenze`,
  geographyNA: "Non applicabile: l'elemento non ha geometria",
  contains: "si trova in",
  nearby: (n: number) => `${n} elementi entro 100 km`,
  more: (n: number) => `altri ${n.toLocaleString("it-IT")}`,
  showMore: "Mostra altri",
  none: "nessuno",
  prev: "precedente",
  next: "successivo",
  openFocus: "Metti a fuoco",
  why: "WHY",
  whyTitle: "WHY THIS RELATION?",
  whyBack: "Torna all'elemento",
  causal: "Associazione: non indica un rapporto di causa.",
  whyRule: "Regola",
  whyRuleActive: "attiva in questo mondo",
  whyRuleNewer: (v: string) => `esiste una versione più recente (${v})`,
  whyCandidates: "Candidati considerati",
  whyGrouping: "Raggruppamento",
  whyRepresentative: "Rappresentante",
  whyRejected: "Scartati",
  whyConfidence: "Confidenza e fattori",
  whyEvidence: "Evidenze",
  whyIndependent: "Fonti indipendenti",
  whyComponents: "Componenti",
  whyUsedBy: "Usata da",
  whyLimitations: "Limiti noti",
  whyMembers: "Membri del pattern",
  notRecorded: "non registrato",
  notApplicable: "non applicabile",
  recomputedOk: (v: string) => `ricalcolato ${v} = memorizzato ✓`,
  recomputedKo: (a: string, b: string) => `ricalcolato ${a} ≠ memorizzato ${b}`,
  groupSupportBy: (v: string) => `supporto del gruppo ${v} fornito da`,
  notIndependent: "non indipendente",
  derivation: "Derivazione",
  explanationGenerated: "enunciato generato dai riferimenti",
  rawRecord: "Record originale",
  rawOpen: "Mostra il record originale",
  rawHide: "Nascondi il record",
  licence: "Licenza",
  fetched: "acquisito",
  graph: {
    depth: "Profondità",
    budgetLabel: "Nodi max",
    phoneLimits: "prof. 1 · max 100",
    filters: "Filtri",
    omitted: (n: number) => `${n} nodi omessi per rispettare il budget`,
    nodes: (n: number, e: number) => `${n} nodi · ${e} archi`,
    budget: (n: number, e: number) => `budget ${n} / ${e}`,
    aggregate: (n: number, t: string) => `+${n.toLocaleString("it-IT")} ${t}`,
    nextPage: "Pagina successiva",
    pageOf: (a: number, b: number) => `pagina ${a} di ${b}`,
    pathTo: "Percorso verso il secondo elemento",
    pathHint: "Maiusc+clic su un secondo elemento per il percorso",
    pathNone: "Nessun percorso entro 4 passaggi",
    pathFound: (h: number) => `Percorso di ${h} passaggi`,
    keepPath: "Tieni solo il percorso",
    recenter: "Ricentra",
    clear: "Pulisci",
    expand: "Espandi",
    tooMany: "Espansione oltre il limite di 2.000 nodi: filtra per tipo o finestra, o apri un nodo aggregato",
    noFocus: "Seleziona un elemento per vederne le relazioni",
    edgeKinds: { relation: "relazione", participation: "partecipazione", insight_member: "membro di insight",
      hypothesis: "ipotesi" } as Record<string, string>,
    layout: "layout deterministico",
    insightsToggle: "Insight",
  },
  time: {
    bucket: { hour: "ora", day: "giorno", week: "settimana", month: "mese", year: "anno" } as Record<string, string>,
    focusTrack: "fuoco",
    relatedTrack: "correlati",
    density: "densità",
    brushHint: "Trascina per impostare la finestra · rotella per lo zoom",
    reset: "Tutto il periodo",
    noTime: "Nessun evento nel mondo",
  },
  status: {
    version: "versione del mondo",
    sourcesOk: (a: number, b: number) => `fonti ${a}/${b}`,
    data: "Dati",
  },
  mobileBack: "Indietro",
  openRail: "Filtri",
  closePanel: "Chiudi",
  about: "Informazioni",
  keyboard: "Tastiera: / cerca · [ ] trail · W perché · M mappa · G grafo · Esc chiudi",
} as const;
