"""DATA PRESERVATION GATE of the OSIRIS-level transformation (2026-10-04): an inventory of NEXUM's information
(database, published snapshot, configuration) that is written before the transformation (PRE) and after it (POST),
and compared. Any loss that is not declared is a FAIL.

    python3 bench/osiris/data_baseline.py write PRE   → bench/osiris/baseline-PRE.json + NEXUM-PRE-OSIRIS-DATA-BASELINE.md
    python3 bench/osiris/data_baseline.py write POST  → bench/osiris/baseline-POST.json + NEXUM-POST-OSIRIS-DATA-BASELINE.md
    python3 bench/osiris/data_baseline.py compare     → exit 1 on any loss"""

import json
import pathlib
import sqlite3
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DB = ROOT / "data" / "live" / "nexum.db"
SNAP = ROOT / "data" / "snapshot" / "live"


def q(c, sql, *a):
    return c.execute(sql, a).fetchall()


def inventory():
    c = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    inv = {}
    for t in ("object", "event", "relation", "evidence", "claim", "insight", "identifier", "alias", "record", "raw_record", "source"):
        inv[f"count.{t}"] = q(c, f"SELECT COUNT(*) FROM {t}")[0][0]
    inv["objects_by_type"] = dict(q(c, "SELECT type, COUNT(*) FROM object WHERE status!='retracted' GROUP BY 1 ORDER BY 1"))
    inv["events_by_type"] = dict(q(c, "SELECT type, COUNT(*) FROM event GROUP BY 1 ORDER BY 1"))
    inv["relations_by_type"] = dict(q(c, "SELECT type, COUNT(*) FROM relation GROUP BY 1 ORDER BY 1"))
    inv["insights_by_rule"] = dict(q(c, "SELECT rule_id, COUNT(*) FROM insight WHERE status='active' GROUP BY 1 ORDER BY 1"))
    inv["objects_by_source"] = dict(q(c, "SELECT source_id, COUNT(*) FROM object GROUP BY 1 ORDER BY 1"))
    inv["indicators"] = dict(q(c, "SELECT json_extract(props_json,'$.indicator'), json_extract(props_json,'$.coverage_n') FROM object "
                                  "WHERE type='observation.indicator' ORDER BY 1"))
    inv["webcams_by_availability"] = dict(q(c, "SELECT json_extract(props_json,'$.availability'), COUNT(*) FROM object "
                                              "WHERE type='camera.public_webcam' GROUP BY 1 ORDER BY 1"))
    inv["webcams_by_source"] = dict(q(c, "SELECT source_id, COUNT(*) FROM object WHERE type='camera.public_webcam' GROUP BY 1 ORDER BY 1"))
    inv["fuel_countries"] = q(c, "SELECT COUNT(DISTINCT json_extract(props_json,'$.country_iso2')) FROM object WHERE type='observation.fuel_price'")[0][0]
    inv["countries"] = q(c, "SELECT COUNT(*) FROM object WHERE type='place.country'")[0][0]
    inv["settlements_with_timezone"] = q(c, "SELECT COUNT(*) FROM object WHERE type='place.settlement' AND json_extract(props_json,'$.timezone') IS NOT NULL")[0][0]
    inv["energy_flow_relations"] = q(c, "SELECT COUNT(*) FROM relation WHERE type IN ('imports_gas_from','imports_crude_from','imports_electricity_from','exports_electricity_to')")[0][0]
    inv["registered_sources"] = len(list((ROOT / "sources").glob("*.toml"))) + len(list((ROOT / "sources_live").glob("*.toml")))
    cur = json.loads((SNAP / "current.json").read_text())
    d = SNAP / "s" / cur["version"]
    inv["snapshot.version"] = cur["version"]
    inv["snapshot.files"] = sum(1 for p in d.rglob("*") if p.is_file())
    api = d / "api"
    for name in ("security", "event-webcams", "places-index", "observations", "tenures", "indicators-catalog", "highlights"):
        f = api / f"{name}.json"
        if f.exists():
            b = json.loads(f.read_text())
            dd = b.get("data", {})
            inv[f"api.{name}.bytes"] = len(f.read_bytes())
            if name == "security":
                inv["security.zones"] = len(dd.get("zones", []))
            if name == "places-index":
                inv["places_index.entries"] = len(dd.get("places", []))
            if name == "tenures":
                inv["tenures.offices"] = len(dd.get("offices", {}))
            if name == "indicators-catalog":
                inv["indicators_catalog.entries"] = len(dd.get("catalog", []))
    img = json.loads((ROOT / "ui" / "src" / "config" / "imagery.json").read_text())
    inv["imagery.products"] = sorted(k for k in img if isinstance(img[k], dict))
    tables = {}
    for f in sorted((api / "tables").glob("*.json")) if (api / "tables").exists() else []:
        try:
            tables[f.stem] = len(json.loads(f.read_text()).get("data", {}).get("rows", []))
        except ValueError:
            pass
    inv["published_tables"] = tables
    hosts = json.loads((ROOT / "ui" / "media-hosts.json").read_text())
    inv["media.hosts"] = {k: len(v) for k, v in hosts.items() if isinstance(v, list)}
    return inv


def md(inv, tag):
    lines = [f"# NEXUM — {tag}-OSIRIS data baseline", "",
             f"Generated by `bench/osiris/data_baseline.py write {tag}` from `data/live/nexum.db` and the published snapshot "
             f"`{inv['snapshot.version']}`. The JSON twin is `bench/osiris/baseline-{tag}.json`.", ""]
    lines += ["| Measure | Value |", "|---|---|"]
    for k, v in inv.items():
        if not isinstance(v, (dict, list)):
            lines.append(f"| {k} | {v:,} |".replace(",", ".") if isinstance(v, int) else f"| {k} | {v} |")
    for k, v in inv.items():
        if isinstance(v, dict):
            lines += ["", f"## {k}", "", "| Key | Value |", "|---|---|"] + [f"| {a} | {b} |" for a, b in v.items()]
        elif isinstance(v, list):
            lines += ["", f"## {k}", "", ", ".join(map(str, v))]
    return "\n".join(lines) + "\n"


def compare(base="PRE"):
    pre = json.loads((ROOT / f"bench/osiris/baseline-{base}.json").read_text())
    post = json.loads((ROOT / "bench/osiris/baseline-POST.json").read_text())
    losses = []
    for k, v in pre.items():
        w = post.get(k)
        if isinstance(v, int) and k not in ("snapshot.files",) and not k.startswith("api."):
            if w is None or w < v:
                losses.append((k, v, w))
        elif isinstance(v, dict):
            for a, b in v.items():
                if k == "published_tables":     # live tables: rows vary with the hour; a table must still exist
                    if a not in (w or {}):
                        losses.append((f"{k}.{a}", b, None))
                    continue
                if isinstance(b, (int, float)) and ((w or {}).get(a) is None or (w or {}).get(a) < b):
                    losses.append((f"{k}.{a}", b, (w or {}).get(a)))
        elif isinstance(v, list) and not set(v) <= set(w or []):
            losses.append((k, v, w))
    for x in losses:
        print("LOSS", *x)
    print("losses:", len(losses))
    return 1 if losses else 0


if __name__ == "__main__":
    if sys.argv[1] == "write":
        tag = sys.argv[2]
        inv = inventory()
        (ROOT / f"bench/osiris/baseline-{tag}.json").write_text(json.dumps(inv, indent=1, ensure_ascii=False))
        if tag in ("PRE", "POST"):
            (ROOT / f"NEXUM-{tag}-OSIRIS-DATA-BASELINE.md").write_text(md(inv, tag))
        print(json.dumps({k: v for k, v in inv.items() if not isinstance(v, (dict, list))}, indent=1))
    else:
        sys.exit(compare(sys.argv[2] if len(sys.argv) > 2 else "PRE"))
